# Generated by Django 3.0.2 on 2020-03-11 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('pan_vat', models.ImageField(upload_to='')),
                ('is_client', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('licence', models.ImageField(upload_to='pics')),
                ('is_customer', models.BooleanField(default=False)),
            ],
        ),
    ]
