# Generated by Django 3.0.2 on 2020-03-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_order_no_of_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='no_of_vehicle',
            field=models.IntegerField(default=1),
        ),
    ]
