# Generated by Django 3.0.2 on 2020-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='available',
            field=models.BooleanField(default='True'),
        ),
    ]
